import { v4 as uuidv4 } from "uuid";

// get current time in milliseconds since Jan, 1 1970
const date =  new Date().getTime();

export const demoExpenses: { id: string, transactionType: string, date: Date, category: string, transactionDescription: string, cost: number }[] = [
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 1)),
      category: "Transportation",
      transactionDescription: "Speedway @ Middletown",
      cost: -23.64,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 1)),
      category: "Groceries",
      transactionDescription: "Walmart @ Westport rd",
      cost: -112.78,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 2)),
      category: "Restaurant",
      transactionDescription: "Chipotle",
      cost: -8.06,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 3)),
      category: "Wardrobe",
      transactionDescription: "Macys",
      cost: -31.44,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 3)),
      category: "Pet",
      transactionDescription: "PetCo @ Middletown",
      cost: -26.11,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 4)),
      category: "Entertainment",
      transactionDescription: "Bought Fishing Poles",
      cost: -64.36,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 4)),
      category: "Groceries",
      transactionDescription: "Costco @ HW42",
      cost: -112.78,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 6)),
      category: "Restaurant",
      transactionDescription: "Panera",
      cost: -10.09,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 7)),
      category: "Wardrobe",
      transactionDescription: "Amazon",
      cost: -42.11,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 7)),
      category: "Pet",
      transactionDescription: "Catnip Toy",
      cost: -3.06,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 8)),
      category: "Groceries",
      transactionDescription: "Fresh Time",
      cost: -65.78,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 9)),
      category: "Groceries",
      transactionDescription: "Costco",
      cost: -200.36,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 11)),
      category: "Groceries",
      transactionDescription: "Tea from Online",
      cost: -96.22,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 13)),
      category: "Transportation",
      transactionDescription: "Gas @ Costco",
      cost: -21.65,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 13)),
      category: "Entertainment",
      transactionDescription: "Spotify Prescription",
      cost: -12.99,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 14)),
      category: "Wardrobe",
      transactionDescription: "Shoe Carnival",
      cost: -62.78,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 14)),
      category: "Wardrobe",
      transactionDescription: "TJMaxx",
      cost: -45.74,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 14)),
      category: "Restaurant",
      transactionDescription: "Chipotle",
      cost: -8.06,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 15)),
      category: "Insurance",
      transactionDescription: "Car",
      cost: -107.36,
    },
    {
      id: uuidv4(),
      transactionType: "Expense",
      date: new Date(date- (1000 * 60 * 60 * 24 * 15)),
      category: "Groceries",
      transactionDescription: "Kroger @ Clifton",
      cost: -32.28,
    },
  ];