import { v4 as uuidv4 } from "uuid";

export const demoExpenses = [
    {
      id: uuidv4(),
      date: "7/15/2023",
      category: "Transportation",
      descriptionOrLocation: "Speedway @ Middletown",
      cost: 23.64,
    },
    {
      id: uuidv4(),
      date: "7/15/2023",
      category: "Groceries",
      descriptionOrLocation: "Walmart @ Westport rd",
      cost: 112.78,
    },
    {
      id: uuidv4(),
      date: "7/17/2023",
      category: "Restaurant",
      descriptionOrLocation: "Chipotle",
      cost: 8.06,
    },
    {
      id: uuidv4(),
      date: "7/17/2023",
      category: "Wardrobe",
      descriptionOrLocation: "Macys",
      cost: 31.44,
    },
    {
      id: uuidv4(),
      date: "7/17/2023",
      category: "Pet",
      descriptionOrLocation: "PetCo @ Middletown",
      cost: 26.11,
    },
    {
      id: uuidv4(),
      date: "7/21/2023",
      category: "Entertainment",
      descriptionOrLocation: "Bought Fishing Poles",
      cost: 64.36,
    },
    {
      id: uuidv4(),
      date: "7/21/2023",
      category: "Groceries",
      descriptionOrLocation: "Costco @ HW42",
      cost: 112.78,
    },
    {
      id: uuidv4(),
      date: "7/21/2023",
      category: "Restaurant",
      descriptionOrLocation: "Panera",
      cost: 10.09,
    },
    {
      id: uuidv4(),
      date: "7/23/2023",
      category: "Wardrobe",
      descriptionOrLocation: "Amazon",
      cost: 42.11,
    },
    {
      id: uuidv4(),
      date: "7/24/2023",
      category: "Pet",
      descriptionOrLocation: "Catnip Toy",
      cost: 3.06,
    },
    {
      id: uuidv4(),
      date: "7/24/2023",
      category: "Groceries",
      descriptionOrLocation: "Fresh Time",
      cost: 65.78,
    },
    {
      id: uuidv4(),
      date: "7/25/2023",
      category: "Groceries",
      descriptionOrLocation: "Costco",
      cost: 200.36,
    },
    {
      id: uuidv4(),
      date: "7/25/2023",
      category: "Groceries",
      descriptionOrLocation: "Tea from Online",
      cost: 96.22,
    },
    {
      id: uuidv4(),
      date: "7/25/2023",
      category: "Transportation",
      descriptionOrLocation: "Gas @ Costco",
      cost: 21.65,
    },
    {
      id: uuidv4(),
      date: "7/26/2023",
      category: "Entertainment",
      descriptionOrLocation: "Spotify Prescription",
      cost: 12.99,
    },
    {
      id: uuidv4(),
      date: "7/26/2023",
      category: "Wardrobe",
      descriptionOrLocation: "Shoe Carnival",
      cost: 62.78,
    },
    {
      id: uuidv4(),
      date: "7/26/2023",
      category: "Wardrobe",
      descriptionOrLocation: "TJMaxx",
      cost: 45.74,
    },
    {
      id: uuidv4(),
      date: "7/26/2023",
      category: "Restaurant",
      descriptionOrLocation: "Chipotle",
      cost: 8.06,
    },
    {
      id: uuidv4(),
      date: "7/28/2023",
      category: "Insurance",
      descriptionOrLocation: "Car",
      cost: 107.36,
    },
    {
      id: uuidv4(),
      date: "7/28/2023",
      category: "Groceries",
      descriptionOrLocation: "Kroger @ Clifton",
      cost: 32.28,
    },
  ];